### PR TITLE
Add configuration option to only highlight one column.

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by whatyouhide** [comment]
Thanks @lewis6991! Can we have some documentation for this option in the README as well?

**Comment by lewis6991** [comment]
Yeah sure I'll update the readme. From my experience `colorcolumn` highlights every row, not just the rows that are long. Thats with `set cc=80`.

**Comment by lewis6991** [comment]
Whoops I accidentally killed some white space. Was this white space required?

**Comment by whatyouhide** [comment]
@lewis6991 yep, it was required because some Markdown engines consider two trailing spaces as a forced line break. :)

**Comment by lewis6991** [comment]
There you go. I added some missing trailing whitespace for consistency.

**Comment by whatyouhide** [comment]
Thanks a lot @lewis6991! 💟

**Pull request merged**
